language: python
python:
 - "3.4"

install: "pip install -r requirements.txt"

before_script:
 - "rm /home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python3.4/site-packages/django_mailbox/admin.py"
 - "rm /home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python3.4/site-packages/django_mailbox/models.py"
 - "rm /home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python3.4/site-packages/django_mailbox/migrations/0*.*"
 - "cp /azam-a/batcher/patches/django_mailbox/admin.py /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django_mailbox/admin.py"
 - "cp /azam-a/batcher/patches/django_mailbox/models.py /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django_mailbox/models.py"
 - "cp /azam-a/batcher/patches/django_mailbox/migrations/ /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django_mailbox/migrations/"

script:
 - "python manage.py test batch_apps"
